// The 151, and how a Red-version player can reach each one.
//
// Derived from PokeAPI, not from memory: per-species wild/gift/fossil/in-game-
// trade encounters for the `red` and `blue` versions, closed over every
// non-trade evolution trigger (level-up, use-item). `trade` marks the four
// species that only evolve while being traded, so no single cartridge can
// produce them at all. Counts are pinned in spec/dex.test.ts.
//
//   both  124   reachable on either cartridge
//   red    11   Red exclusive
//   blue   11   Blue exclusive, so unreachable alone on Red
//   trade   4   only evolves mid-trade
//   never   1   Mew, never released in normal play

export type Origin = "both" | "red" | "blue" | "trade" | "never";

export interface Entry {
  readonly no: number;
  readonly name: string;
  readonly origin: Origin;
}

export const DEX: readonly Entry[] = [
  { no: 1, name: "Bulbasaur", origin: "both" },
  { no: 2, name: "Ivysaur", origin: "both" },
  { no: 3, name: "Venusaur", origin: "both" },
  { no: 4, name: "Charmander", origin: "both" },
  { no: 5, name: "Charmeleon", origin: "both" },
  { no: 6, name: "Charizard", origin: "both" },
  { no: 7, name: "Squirtle", origin: "both" },
  { no: 8, name: "Wartortle", origin: "both" },
  { no: 9, name: "Blastoise", origin: "both" },
  { no: 10, name: "Caterpie", origin: "both" },
  { no: 11, name: "Metapod", origin: "both" },
  { no: 12, name: "Butterfree", origin: "both" },
  { no: 13, name: "Weedle", origin: "both" },
  { no: 14, name: "Kakuna", origin: "both" },
  { no: 15, name: "Beedrill", origin: "both" },
  { no: 16, name: "Pidgey", origin: "both" },
  { no: 17, name: "Pidgeotto", origin: "both" },
  { no: 18, name: "Pidgeot", origin: "both" },
  { no: 19, name: "Rattata", origin: "both" },
  { no: 20, name: "Raticate", origin: "both" },
  { no: 21, name: "Spearow", origin: "both" },
  { no: 22, name: "Fearow", origin: "both" },
  { no: 23, name: "Ekans", origin: "red" },
  { no: 24, name: "Arbok", origin: "red" },
  { no: 25, name: "Pikachu", origin: "both" },
  { no: 26, name: "Raichu", origin: "both" },
  { no: 27, name: "Sandshrew", origin: "blue" },
  { no: 28, name: "Sandslash", origin: "blue" },
  { no: 29, name: "Nidoran\u2640", origin: "both" },
  { no: 30, name: "Nidorina", origin: "both" },
  { no: 31, name: "Nidoqueen", origin: "both" },
  { no: 32, name: "Nidoran\u2642", origin: "both" },
  { no: 33, name: "Nidorino", origin: "both" },
  { no: 34, name: "Nidoking", origin: "both" },
  { no: 35, name: "Clefairy", origin: "both" },
  { no: 36, name: "Clefable", origin: "both" },
  { no: 37, name: "Vulpix", origin: "blue" },
  { no: 38, name: "Ninetales", origin: "blue" },
  { no: 39, name: "Jigglypuff", origin: "both" },
  { no: 40, name: "Wigglytuff", origin: "both" },
  { no: 41, name: "Zubat", origin: "both" },
  { no: 42, name: "Golbat", origin: "both" },
  { no: 43, name: "Oddish", origin: "red" },
  { no: 44, name: "Gloom", origin: "red" },
  { no: 45, name: "Vileplume", origin: "red" },
  { no: 46, name: "Paras", origin: "both" },
  { no: 47, name: "Parasect", origin: "both" },
  { no: 48, name: "Venonat", origin: "both" },
  { no: 49, name: "Venomoth", origin: "both" },
  { no: 50, name: "Diglett", origin: "both" },
  { no: 51, name: "Dugtrio", origin: "both" },
  { no: 52, name: "Meowth", origin: "blue" },
  { no: 53, name: "Persian", origin: "blue" },
  { no: 54, name: "Psyduck", origin: "both" },
  { no: 55, name: "Golduck", origin: "both" },
  { no: 56, name: "Mankey", origin: "red" },
  { no: 57, name: "Primeape", origin: "red" },
  { no: 58, name: "Growlithe", origin: "red" },
  { no: 59, name: "Arcanine", origin: "red" },
  { no: 60, name: "Poliwag", origin: "both" },
  { no: 61, name: "Poliwhirl", origin: "both" },
  { no: 62, name: "Poliwrath", origin: "both" },
  { no: 63, name: "Abra", origin: "both" },
  { no: 64, name: "Kadabra", origin: "both" },
  { no: 65, name: "Alakazam", origin: "trade" },
  { no: 66, name: "Machop", origin: "both" },
  { no: 67, name: "Machoke", origin: "both" },
  { no: 68, name: "Machamp", origin: "trade" },
  { no: 69, name: "Bellsprout", origin: "blue" },
  { no: 70, name: "Weepinbell", origin: "blue" },
  { no: 71, name: "Victreebel", origin: "blue" },
  { no: 72, name: "Tentacool", origin: "both" },
  { no: 73, name: "Tentacruel", origin: "both" },
  { no: 74, name: "Geodude", origin: "both" },
  { no: 75, name: "Graveler", origin: "both" },
  { no: 76, name: "Golem", origin: "trade" },
  { no: 77, name: "Ponyta", origin: "both" },
  { no: 78, name: "Rapidash", origin: "both" },
  { no: 79, name: "Slowpoke", origin: "both" },
  { no: 80, name: "Slowbro", origin: "both" },
  { no: 81, name: "Magnemite", origin: "both" },
  { no: 82, name: "Magneton", origin: "both" },
  { no: 83, name: "Farfetch'd", origin: "both" },
  { no: 84, name: "Doduo", origin: "both" },
  { no: 85, name: "Dodrio", origin: "both" },
  { no: 86, name: "Seel", origin: "both" },
  { no: 87, name: "Dewgong", origin: "both" },
  { no: 88, name: "Grimer", origin: "both" },
  { no: 89, name: "Muk", origin: "both" },
  { no: 90, name: "Shellder", origin: "both" },
  { no: 91, name: "Cloyster", origin: "both" },
  { no: 92, name: "Gastly", origin: "both" },
  { no: 93, name: "Haunter", origin: "both" },
  { no: 94, name: "Gengar", origin: "trade" },
  { no: 95, name: "Onix", origin: "both" },
  { no: 96, name: "Drowzee", origin: "both" },
  { no: 97, name: "Hypno", origin: "both" },
  { no: 98, name: "Krabby", origin: "both" },
  { no: 99, name: "Kingler", origin: "both" },
  { no: 100, name: "Voltorb", origin: "both" },
  { no: 101, name: "Electrode", origin: "both" },
  { no: 102, name: "Exeggcute", origin: "both" },
  { no: 103, name: "Exeggutor", origin: "both" },
  { no: 104, name: "Cubone", origin: "both" },
  { no: 105, name: "Marowak", origin: "both" },
  { no: 106, name: "Hitmonlee", origin: "both" },
  { no: 107, name: "Hitmonchan", origin: "both" },
  { no: 108, name: "Lickitung", origin: "both" },
  { no: 109, name: "Koffing", origin: "both" },
  { no: 110, name: "Weezing", origin: "both" },
  { no: 111, name: "Rhyhorn", origin: "both" },
  { no: 112, name: "Rhydon", origin: "both" },
  { no: 113, name: "Chansey", origin: "both" },
  { no: 114, name: "Tangela", origin: "both" },
  { no: 115, name: "Kangaskhan", origin: "both" },
  { no: 116, name: "Horsea", origin: "both" },
  { no: 117, name: "Seadra", origin: "both" },
  { no: 118, name: "Goldeen", origin: "both" },
  { no: 119, name: "Seaking", origin: "both" },
  { no: 120, name: "Staryu", origin: "both" },
  { no: 121, name: "Starmie", origin: "both" },
  { no: 122, name: "Mr. Mime", origin: "both" },
  { no: 123, name: "Scyther", origin: "red" },
  { no: 124, name: "Jynx", origin: "both" },
  { no: 125, name: "Electabuzz", origin: "red" },
  { no: 126, name: "Magmar", origin: "blue" },
  { no: 127, name: "Pinsir", origin: "blue" },
  { no: 128, name: "Tauros", origin: "both" },
  { no: 129, name: "Magikarp", origin: "both" },
  { no: 130, name: "Gyarados", origin: "both" },
  { no: 131, name: "Lapras", origin: "both" },
  { no: 132, name: "Ditto", origin: "both" },
  { no: 133, name: "Eevee", origin: "both" },
  { no: 134, name: "Vaporeon", origin: "both" },
  { no: 135, name: "Jolteon", origin: "both" },
  { no: 136, name: "Flareon", origin: "both" },
  { no: 137, name: "Porygon", origin: "both" },
  { no: 138, name: "Omanyte", origin: "both" },
  { no: 139, name: "Omastar", origin: "both" },
  { no: 140, name: "Kabuto", origin: "both" },
  { no: 141, name: "Kabutops", origin: "both" },
  { no: 142, name: "Aerodactyl", origin: "both" },
  { no: 143, name: "Snorlax", origin: "both" },
  { no: 144, name: "Articuno", origin: "both" },
  { no: 145, name: "Zapdos", origin: "both" },
  { no: 146, name: "Moltres", origin: "both" },
  { no: 147, name: "Dratini", origin: "both" },
  { no: 148, name: "Dragonair", origin: "both" },
  { no: 149, name: "Dragonite", origin: "both" },
  { no: 150, name: "Mewtwo", origin: "both" },
  { no: 151, name: "Mew", origin: "never" },
];
